Evgen.starostenko/homework2
evgenstarostenkoo/Cypress_training pull request #4
Opened 2022-07-20 22:43 UTC by evgenstarostenkoo

2022-07-25 06:57 UTC, ievgendco requested changes

2022-07-25 06:57 UTC, ievgendco commented on cypress/e2e/Tests/sign_in_test.spec.js
> +    for (let i = 0; i < 10; i++)
Please migrate it to the separate method in helper

2022-07-25 06:57 UTC, ievgendco commented on cypress/e2e/Tests/sign_in_test.spec.js
> +    it('Show typeable "UserName" field', () => {
Add one space between tests

2022-07-25 14:15 UTC, anatolygusakovsky1 requested changes

2022-07-25 14:15 UTC, anatolygusakovsky1 commented on cypress/support/commands.js
> +export const myRandomString = () => {
Do not store non-cypress functions in cypress/support/commands.js.
Feel free to create new file/folder+file in cypress directory and put it there

2022-07-25 14:33 UTC, evgenstarostenkoo commented on cypress/support/commands.js
> +export const myRandomString = () => {
Fixed, please review

2022-08-02 19:06 UTC, anatoly-devico approved these changes
Approved

2022-08-04 10:27 UTC, merged